[workspace]
resolver = "2"
members = [
  "crates/tdsl-parser",
  "crates/tdsl-core",
  "crates/tdsl-wikidata",
  "crates/tdsl-render",
  "crates/tdsl-cli",
  "crates/tdsl-wasm",
  "crates/tdsl-lsp",
]

[workspace.package]
version = "1.28.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/keroway/timeline-dsl"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "1"
thiserror = "2"
miette = { version = "7", features = ["fancy"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
